site_name: RMoney API Documentation

theme:
  name: material
  custom_dir: overrides
  logo: images/logo.png
  features:
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.expand
    - search.suggest
    - search.highlight
    - toc.follow
    - content.code.copy
    - content.tabs.link

  palette:
    - scheme: default
      primary: white
      accent: deep orange

nav:
  - Home: index.md

  - Getting Started:
      - Introducton: GS/intro.md

  - Interactive API:
      - Overview: interactive/overview.md
      - User: interactive/user/user.md
      - Authentication: interactive/Authentication.md
      - Base URL & Endpoints: interactive/baseurl.md
      - Data Types & Business Rules: interactive/DataTypes&BussinessRules.md
      - Rate Limit: interactive/RateLimit.md

      - Enums With Numeric Constants: interactive/EnumsWithNumericConstants.md
      - Standard Orders:
        - Overview: interactive/orders/overview.md
        - Place Order: interactive/orders/place_order.md
        - Cancel Order: interactive/orders/cancel_order.md
        - Cancel All Orders: interactive/orders/cancelall.md
        - Modify Order: interactive/orders/modify_order.md
      - Cover Orders: interactive/CoverOrders.md
      - Bracket Orders: interactive/BracketOrders.md
      - Spread Orders: interactive/SpreadOrders.md
      - Portfolio:
        - Overview: interactive/portfolio/overview.md
        - Holdings: interactive/portfolio/holdings.md
        - Positions: interactive/portfolio/positions.md
        - Position Convert: interactive/portfolio/position_convert.md
        - Funds: interactive/portfolio/funds.md
      - Tradebook & Orderbook:
        - Order History: interactive/tradebook/history.md
        - Orderbook: interactive/tradebook/orderbook.md
        - Tradebook: interactive/tradebook/tradebook.md
      - GTT Orders: interactive/GTTOrders.md
      - Margin Calculator: interactive/MarginCalculator.md
      - MTM Calculation: interactive/MTMCalculation.md
      - Error Codes: interactive/errors.md
      - Socket Streaming: interactive/SocketStreaming.md
      - Exchange Messages: interactive/EM.md
      - Exchange Status: interactive/ES.md


  - Market Data API:
      - Overview: market/overview.md
      - Auth: market/Auth.md
      - Data Types & Bussiness Rules: market/Data.md
      - Enums With Numeric Constants: market/Enums.md
      - Client Config: market/CC.md
      - Search:
        - Overview: market/Search/Search.md
        - Instrument By ID: market/Search/instrumentbyid.md
        - Instrument By Search String: market/Search/instrumentbysearchstring.md
      - Instruments:
        - Overview: market/Instruments/instruments.md
        - Master: market/Instruments/master.md
        - Quote: market/Instruments/quote.md
        - GetIndexList: market/Instruments/GetIndexList.md
        - GetSeries: market/Instruments/GetSeries.md
        - GetEquitySymbol: market/Instruments/GetEquitySymbol.md
        - GetExpiryDate: market/Instruments/GetExpiryDate.md
        - GetFutureSymbol: market/Instruments/GetFutureSymbol.md
        - GetOptionType: market/Instruments/GetOptionType.md
        - GetStrikePrice: market/Instruments/GetStrikePrice.md
        - GetOptionSymbol: market/Instruments/GetOptionSymbol.md
      - OHLC Data: market/ohlc.md 
      - Market Depth: market/depth.md
      - Socket Streaming: market/SS.md
      - Socket Subscription: market/SSub.md
      
  - WebSocket:
      - Overview: websocket/overview.md
      - Connection: websocket/connection.md
      - Events: websocket/events.md

  - Reference:
      - Overview: references/overview.md
      - Enums: references/enums.md
      - Constants: references/constants.md
      - Helper Functions: references/helperfunctions.md
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/home.js
  - javascripts/lightbox.js
  - javascripts/toc-highlight.js
  - javascripts/float-cards.js
  - javascripts/toc-orange.js
